# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0002_remove_vehicle_identify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, max_length=10, null=True),
        ),
    ]
