# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0003_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
