# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0010_auto_20190304_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(upload_to='car'),
        ),
    ]
