# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0011_auto_20190304_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1024)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carride.Vehicle')),
            ],
        ),
    ]
