# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='car',
        ),
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
