# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0013_auto_20190306_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
