# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0014_auto_20190307_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carride.Vehicle'),
        ),
    ]
