# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0015_review_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carride.Vehicle'),
        ),
    ]
