# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0016_auto_20190307_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
    ]
