# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0017_remove_review_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='forSale',
            field=models.BooleanField(default=True),
        ),
    ]
