# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0018_vehicle_forsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
