# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0019_vehicle_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carride.Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
