# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0020_auto_20190310_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
