# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0021_auto_20190310_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
