# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0024_auto_20190311_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='car/'),
        ),
    ]
