# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0028_auto_20190317_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=256),
        ),
    ]
