# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0027_auto_20190316_2237'),
        ('carride', '0029_auto_20190317_1611'),
    ]

    operations = [
    ]
