# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0030_merge_20190317_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True, verbose_name=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)),
        ),
    ]
