# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 18:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0032_auto_20190318_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
