# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0035_vehicle_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='poster',
        ),
    ]
