# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0036_remove_vehicle_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
