# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0031_auto_20190318_1658'),
        ('carride', '0037_auto_20190319_1850'),
    ]

    operations = [
    ]
