# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0040_auto_20190320_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='numplate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
