# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0041_vehicle_numplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='numplate',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
