# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0038_merge_20190320_1613'),
        ('carride', '0042_auto_20190320_1653'),
    ]

    operations = [
    ]
