# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carride', '0048_auto_20190322_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='profile_images'),
        ),
    ]
